### ISSUE TITLE
Theme `stackoverflow` print view quirk

### ISSUE THREAD

**Issue by s3rj1k** [jsonresume/jsonresume.org#155]
When trying to print `stackoverflow` based CV, job positions have `JobNameat Place` `at` without space prefix, when viewing this as web page `at` is replaced by `|` with proper spacing.

It would be nice for print view to be fixed with prefix space.

**Comment by s3rj1k** [comment]
ref: https://registry.jsonresume.org/thomasdavis?theme=stackoverflow
![image](https://github.com/user-attachments/assets/6a4d95f2-096f-44cf-8e2c-31f3e7a101a8)
vs
![image](https://github.com/user-attachments/assets/1fad132c-3010-44b4-9c95-1ecd7134c80b)

**Comment by levino** [comment]
You mean https://github.com/jsonresume/jsonresume.org/pull/145 ? :D

**Comment by levino** [comment]
@thomasdavis has not been active recently. I am wondering why that is the case. I am waiting for their approval of #145 out of politeness. Maybe you can chime in @thomasdavis?

**Comment by s3rj1k** [comment]
> You mean https://github.com/jsonresume/jsonresume.org/pull/145 ? :D

Lol

**Comment by levino** [comment]
Closed by #145. Fix released in [2.1.2](https://github.com/jsonresume/jsonresume.org/releases/tag/%40jsonresume/theme-stackoverflow%402.1.2)
