### ISSUE TITLE
replace jekyll with astro

### ISSUE THREAD

**Issue by levino** [jsonresume/jsonresume.org#16]
I recently [migrated](https://github.com/levino/roessing.de/pull/70) one of my websites to [astro](https://astro.build/). I think it is perfect for simple websites and "the new jekyll". Way better than nextjs because of simplicity and [content collections](https://docs.astro.build/en/guides/content-collections/).

I put this here as a basis for discussion, following @thomasdavis [remarks](https://github.com/jsonresume/jsonresume.org/pull/13#issuecomment-1825237994).

**Comment by thomasdavis** [comment]
I haven't used it, but been meaning to. So we might as well. 

The plan was to also make reusable components so that any websites/tools for JSON Resume can just we use, but can abstract when actually needed.
