### ISSUE TITLE
add "jsonresume-theme-stackoverflow-react"

### ISSUE THREAD

**Issue by levino** [jsonresume/jsonresume.org#17]
Also from the [discussion](https://github.com/jsonresume/jsonresume.org/pull/13#issuecomment-1825237994) about react themes: Probably I should link my [theme](https://github.com/levino/jsonresume-theme-stackoverflow-react). It has some quirks to support multiple languages though, but the default English version should be backwards compatible.

**Comment by thomasdavis** [comment]
Oh this would be great to get back on the registry. 

The old broke because the new function hosting doesn't support reading files from disk e.g. handlebars templates

**Comment by levino** [comment]
Done in #35
