### ISSUE TITLE
fiddled with the vercel configurations

### ISSUE THREAD

**Issue by levino** [jsonresume/jsonresume.org#20]
I tweaked the deployment configs in the vercel ui a bit. Just leaving this here as an FYI for @thomasdavis. I tried to leverage turborepo more. I hope it does not break things. Please close this issue once you have read it.

I will be out for today now, got some other stuff to do. Have a nice day!

**Comment by thomasdavis** [comment]
Looks good. just updated the team name too.

**Comment by levino** [comment]
Please update the repository variable "Turbo_team" for the actions as well. I can also do it later.

**Comment by thomasdavis** [comment]
Hrmm the repository settings -> actions variables only has `TURBO_TAKEN`

**Comment by levino** [comment]
That's the secrets. There are variables too.

**Comment by thomasdavis** [comment]
whoops, didn't see the tab for it. updated
