### ISSUE TITLE
please bring back theme called "full"

### ISSUE THREAD

**Issue by levino** [jsonresume/jsonresume.org#46]
please bring back theme called "full"

_Originally posted by @sachsgiri in https://github.com/jsonresume/jsonresume.org/issues/36#issuecomment-1835834487_

**Comment by levino** [comment]
NPM https://www.npmjs.com/package/jsonresume-theme-full
github https://github.com/jackkeller/jsonresume-theme-full#readme

The problem is that the theme is using handlebars@2 which is deprecated and has proven security vulnerabilities. Source code needs to be updated, then we might be able to bring it back.

Do you think you could make a PR for `jsonresume-theme-full` to update the `handlebars` dependency @sachsgiri?

**Comment by thomasdavis** [comment]
fixed in https://github.com/jsonresume/jsonresume.org/pull/47
