### ISSUE TITLE
migrating homepage to nextjs from jekyll

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/jsonresume.org#85]
The jekyll gem that use to work has had issues recently so I've decided to migrate the original homepage to Next.js so we can more easily re-use all the Javascript components anyway. 

It's almost finished, I mostly just have the blog and meta tags to do.

I'm also going to include rearranging and updating the documentation. 

and try to tackle these issues also

https://github.com/jsonresume/jsonresume.org/issues/58
https://github.com/jsonresume/jsonresume.org/issues/23
https://github.com/jsonresume/jsonresume.org/issues/16

**Comment by levino** [comment]
Why not use astro? Better suited for file based cms.
