### ISSUE TITLE
pnpm lint does not work inside of themes/*

### ISSUE THREAD

**Issue by thomasdavis** [jsonresume/jsonresume.org#87]
The error I get is 

```
> @jsonresume/theme-papirus@1.0.1 lint /home/ajax/repos/jsonresume.org/themes/papirus
> eslint .


Oops! Something went wrong! :(

ESLint: 8.54.0

You are linting ".", but all of the files matching the glob pattern "." are ignored.

If you don't want to lint these files, remove the pattern "." from the list of arguments passed to ESLint.

If you do want to lint these files, try the following solutions:

* Check your .eslintignore file, or the eslintIgnore property in package.json, to ensure that the files are not configured to be ignored.
* Explicitly list the files from this glob that you'd like to lint on the command-line, rather than providing a glob as an argument.

```

I've lost too much time trying to fix tonight so I've disabled their individual lints in my PR.

From my understanding, there are no js files in those folders, so generally you would have to set `eslint . --ext cjs` etc but that seems to do nothing also. 

It could be related to a minor or patch update to eslint.

**Comment by levino** [comment]
Could you produce a PR where this check fails? I could then fix it easily, I would dare to bet.

**Comment by levino** [comment]
Also whenever you have such issues, just open a PR and summon me with @levino. I will then try to help you fix it fast. No worries. Better than to have failing checks or ignored code imo.

**Comment by levino** [comment]
Fwiw: You should not run `eslint .` but always `pnpm eslint .`. I recommend removing any global `eslint` installation. You might get version mismatches, which are always a problem. You could also just use `pnpm turbo lint` which is what CI is running.

**Comment by thomasdavis** [comment]
Yeah I am running `pnpm turbo lint` on the branch `new-blog` (the last commits disable the `scripts: lint {}` commands in those theme folders though. let me check if it works on master.

**Comment by thomasdavis** [comment]
I just re-enabled eslint in the broken branch. So to replicate 

```
git checkout new-blog 
cd themes/papirus
pnpm lint
``` 

Gives me 
```
Oops! Something went wrong! :(

ESLint: 8.54.0
```

Currently looking at your latest PR

**Comment by thomasdavis** [comment]
ah sorry, it was my fault, conflating a bunch of bugs and then forgot about this https://github.com/jsonresume/jsonresume.org/commit/f15de1a1507fac34e8b7863a0441af6c11514032 

it should fix it

**Comment by thomasdavis** [comment]
Yeah build working in #84 now. can probably close #88 too. 

thank you!
